Trying to switch up our gateway init.d script.

diff --git a/src/etc/init.d/gateway b/src/etc/init.d/gateway
--- a/src/etc/init.d/gateway
+++ b/src/etc/init.d/gateway
@@ -1,12 +1,87 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          sudomesh-gateway
+# Required-Start:    $local_fs $remote_fs $network $syslog exim4 
+# Required-Stop:     $local_fs $remote_fs $network $syslog exim4
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Sudomesh gateway startup
+# Description:       Start and stop sudomesh gateway 
+### END INIT INFO
 
-# Very simple gateway script. Needs much work.
+# Do NOT "set -e"
 
 ETH=eth0
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DESC="Sudomesh gateway startup"
+NAME=sudomesh-gateway
+SCRIPTNAME=/etc/init.d/$NAME
+DAEMON_USER=root
+DAEMON_GROUP=root
+PIDFILE=/var/run/$NAME.pid
 
-iptables -t nat -A POSTROUTING -o $ETH -j MASQUERADE
-echo 1 > /proc/sys/net/ipv4/ip_forward
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-iptables -A INPUT -m state --state NEW ! -i $ETH -j ACCEPT
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	
+  iptables -t nat -A POSTROUTING -o $ETH -j MASQUERADE
+  echo 1 > /proc/sys/net/ipv4/ip_forward
+
+  iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
+  iptables -A INPUT -m state --state NEW ! -i $ETH -j ACCEPT
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	return 0
+}
+
+case "$1" in
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+		do_start
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			*) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+		;;
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			*) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+		;;
+	*)
+		echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
+		exit 3
+		;;
+esac
+
+:
